### ISSUE TITLE
Test Case name not fully displaying when space is available 

### ISSUE THREAD

**Issue by charlieforward9** [vitest-dev/vscode#368]
### Describe the bug

When I drag the Navigation Bar out to show more text within the test cases, I see the ellipses. This should show the entire test name.

<img width="239" alt="Screenshot 2024-05-01 at 12 57 52 AM" src="https://github.com/vitest-dev/vscode/assets/62311337/537020ab-cd6e-46c1-a5d3-aad1a57806dc">

### Reproduction

```ts
describe("This is a really long test name that will surpass the length of the VSCode Testing navigator display", () => {
  it("should not show all of this text in the VSCode Testing navigator display because of a Vitest limitation", () => {
     expect(testDescriptorSizeLimit).toBe(undefined);
  });
});
```

### Output

A view similar to the one above with two test items showing something like this 

```
This is a really long test name tha...
   should not show all of this text in...
```

### Version

v0.8.6

### Validations

- [X] Check that you are using the latest version of the extension
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
```[tasklist]
### Tasks
```

**Comment by sheremet-va** [comment]
This is how names are reported by Vitest.

**Comment by charlieforward9** [comment]
@sheremet-va thank you for the response. 
Is it possible to change this in Vitest, it would be helpful to see the full string in the navigation bar if it were dragged to the respective width.

**Comment by sheremet-va** [comment]
> Is it possible to change this in Vitest, it would be helpful to see the full string in the navigation bar if it were dragged to the respective width.

Vitest doesn't do _anything_ with the name. This is something done by an external tool before the extension receives the data. I cannot reproduce it with your "reproduction":

<img width="706" alt="Screenshot 2024-05-02 at 10 29 05" src="https://github.com/vitest-dev/vscode/assets/16173870/2e8f6026-6bf7-4f0b-b5d5-930761820173">

**Comment by charlieforward9** [comment]
Im sorry, it seems I misunderstood what you originally said. This seems to be an issue with the vitest-cucumber plugin, or something else I am depending on. Thank you for clarifying.

**Comment by sheremet-va** [comment]
I managed to reproduce it with this code: 

```ts
  it.each([{ key: 'should not show all of this text in the VSCode Testing navigator display because of a Vitest limitation' }])("$key", () => {
     expect(undefined).toBe(undefined);
  });
```

Vitest doesn't expect the full names to be used as properties there as they are treated a bit differently that if it was `%s` for example (which will just be replaced) - it also intentionally puts `'` to signal it as a string. Adding `truncateTreshold` should help:

```ts
export default defineConfig({
  test: {
    chaiConfig: {
      truncateThreshold: Infinity,
    }
  },
})
```

But I would change how the tests are generated on cucumber side.

**Comment by charlieforward9** [comment]
Thank you for the details. I will see about contributing these findings to give back to the community after getting so much support!

**Comment by charlieforward9** [comment]
https://github.com/amiceli/vitest-cucumber/pull/72 is addressing this issue.

**Comment by amiceli** [comment]
I've improved tests title in vitest-cucumber, long title are more legible now.
@sheremet-va tests are sorted alphabetically ?
For example `When` is before `Then`.

<img width="438" alt="image" src="https://github.com/vitest-dev/vscode/assets/5556115/8d824172-56a9-425b-bd2e-5cdac88b0fca">

**Comment by charlieforward9** [comment]
I see this in my own code as well. Changing this to `Sort by location` does not fix it either. 

<img width="188" alt="Screenshot 2024-05-06 at 12 30 56 PM" src="https://github.com/vitest-dev/vscode/assets/62311337/373924b4-21bc-4dc7-bdaf-007ca6f00fae">

**Comment by sheremet-va** [comment]
I need any kind of reproduction that uses vitest-cucumber. From what I remember, the extension sorts by location by default.

**Comment by amiceli** [comment]
I'm creating an example repository.
I finish it and give you its link.

**Comment by amiceli** [comment]
@sheremet-va You can check [vitest-cucumber-example](https://github.com/amiceli/vitest-cucumber-example) project.
When I use vitest on vscode, I see `Then` before `When` for example ;).

Say me if you need more examples inside this project.

**Comment by sheremet-va** [comment]
It doesn't have information about the location (you would've seen the green arrow in this case), so it's sorted by default. I don't think this is the extension's fault.

I will fix the sorting by modifying the `sortText` string, but I would recommend using the official custom API for this instead of wrapping `test` function.

**Comment by sheremet-va** [comment]
Fixed by https://github.com/vitest-dev/vscode/commit/f282283a1273d370b479a85d184c0d95db7e42f1

**Comment by amiceli** [comment]
@sheremet-va Yes, it works on example projet ;).
